on:
  push:
    paths: 
      - ".github/workflows/android-emulator-steps.yaml"

jobs:
  android-emulator:
    runs-on: ubuntu-latest
    name: android emulator
    steps:
      - uses: actions/checkout@v1
      - run: ./1_download_sdk.sh
      - run: ./2_platform_tools.sh
      - run: ./3_sdk_emulator.sh


