# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
      - ".github/workflows/artifact.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir output
          touch output/file1.txt
          touch output/file2.txt
          mkdir output/dir1
          touch output/dir1/file_in_dir.txt
      - uses: actions/upload-artifact@v2
        with: 
          name: job1-arficact
          path: output/**
  download:
    needs: [upload]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: job1-arficact
          path: input
      - run: ls -la input
