# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths: 
      - ".github/workflows/artifact.yml"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          mkdir output
          echo "sample" >> output/file.txt
      - uses: actions/upload-artifact@v2
        with: 
          path: output
  download:
    needs: [upload]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          path: input
      - run: ls -la input
