on:
  push:
    paths: 
      - ".github/workflows/cancel-workflow.yml"

jobs:
  cancel-previous:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.home }}!"
      - uses: tutu-ru-mobile/cancel_workflow@master
        with:
          access_token: "${{ secrets.GITHUB_TOKEN }}"
      - run: |
          echo "sleep 2 minutes"
          sleep 120
          echo "complete!"
      
      

