name: cron
on:
  schedule:
     #- cron: '0 9 * * 1-5' # 12:00 по Москве с понедельника по пятницу
     - cron: '32 10 * * 1-5' # 13:32 по Москва с понедельника по пятницу
  push:
    tags: 
      - "night*"
jobs:
  label:
    strategy:
      matrix:
        os: [ubuntu-18.04] #, macos-latest, windows-latest
        java_version: [1.8] #, 10, 11, 12
    runs-on: ${{ matrix.os }}
    steps:
      - name: date
        run: date
