# copy from: https://github.community/t5/GitHub-Actions/GitHub-Actions-Manual-Trigger-Approvals/m-p/33364#M1478

name: 'Deploy'
on:
  deployment:
  push:
    paths: 
      - ".github/workflows/deployment.yml"

jobs:
  deployment:
    if: github.event.deployment.payload.keyBoolean

    runs-on: 'ubuntu-latest'

    steps:
    - name: 'Checkout'
      uses: 'actions/checkout@v1'

    - name: 'Deployment pending'
      uses: 'deliverybot/status@master'
      with:
        state: 'pending'
        token: '${{ secrets.GITHUB_TOKEN }}'

# do your deployment here, using whatever tooling you like:

    - name: 'Deploy ${{ github.event.deployment.environment }}'
      run: |
        echo "task - ${{ github.event.deployment.task }}"
        echo "environment - ${{ github.event.deployment.environment }}"
        echo "payload - ${{ toJson(github.event.deployment.payload) }}"
        echo "payload.key1 - ${{github.event.deployment.payload.key1}}"

    - name: 'deployment success'
      if: success()
      uses: 'deliverybot/status@master'
      with:
        state: 'success'
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: 'deployment failure'
      if: failure()
      uses: 'deliverybot/status@master'
      with:
        state: 'failure'
        token: '${{ secrets.GITHUB_TOKEN }}' 
