name: ignore_fail
on:
  push:
    paths:
      - ".github/workflows/ignore_fail.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      #continue-on-error: true
      run: exit 1
    - name: continue
      if: always()
      run: |
        echo continue
