name: ignore_fail
on:
  push:
    paths:
      - ".github/workflows/ignore_fail.yml"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1
      #continue-on-error: true
    - run: echo always
      if: always()
    - run: echo condition
      if: succeeded() || failed()
#     - run: echo false
#       if: false
