name: info
on:
  push:
    paths: 
      - ".github/workflows/info.yml"
jobs:
  label:
    strategy:
      matrix:
        os: [ubuntu-18.04] #, macos-latest, windows-latest
        java_version: [1.8] #, 10, 11, 12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/github-script@v4
        id: set-result
        with:
          script: console.log(context.payload);
          result-encoding: string
      
      - uses: actions/github-script@v4
        id: check-timestamp
        with:
          script: |
            console.log(context.payload.head_commit.timestamp);
            console.log(Date.now());
            var lastCommitTimestamp = Date.parse(context.payload.head_commit.timestamp);
            var sinceLastCommit = Date.now() - lastCommitTimestamp;
            console.log("Date.now(): " + Date.now())
            console.log("sinceLastCommit: " + sinceLastCommit)
            console.log(sinceLastCommit + " ms")
            console.log(context)
            github.rest.actions.cancelWorkflowRun({
              context.payload.repository.owner.login,
              context.payload.repository.name,
              ${{github.run_id}},
            });
          result-encoding: string

      - run: $ANDROID_HOME/tools/bin/avdmanager list
      - run: touch empty_file && ls -la
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java_version }}
      - name: system info
        run: |
          df -h
          cat /proc/meminfo
          free -m
      - name: software info
        run: |
          env
          gcloud components list
      - name: cpu stress
        run: |
          docker run containerstack/cpustress --cpu 1 --timeout 10s --metrics-brief

