name: night_check

on:
  workflow_dispatch:
  schedule:
    - cron: "00 23 * * 1-5" #23:00 UTC (это 2:00 ночи по Москве) с понедельника по пятницу
jobs:
  post-merge:
    timeout-minutes: 360
    runs-on: macos-11
    steps:
      - run: echo "hi"
